require "Vehicles/VehicleDistributions"

local function initTrue_Moozic_BHiVehicleDistribution()
    -- read sandbox multiplier for vehicles
    local _sandbox = SandboxVars and SandboxVars["True_Moozic_BHi"] or {}
    local _multVehicle = (_sandbox.VehicleSpawnMultiplier or 1.0)
    if VehicleDistributions and VehicleDistributions.GloveBox then
        table.insert(VehicleDistributions.GloveBox.items, "True_Moozic_BHi.CassetteAFlockOfSeagullsIRanSoFarAway198")
        table.insert(VehicleDistributions.GloveBox.items, 1 * _multVehicle)
        table.insert(VehicleDistributions.GloveBox.items, "True_Moozic_BHi.CassetteATribeCalledQuestCanIKickIt1990")
        table.insert(VehicleDistributions.GloveBox.items, 1 * _multVehicle)
        table.insert(VehicleDistributions.GloveBox.items, "True_Moozic_BHi.CassetteAHaTakeOnMe1985")
        table.insert(VehicleDistributions.GloveBox.items, 1 * _multVehicle)
        table.insert(VehicleDistributions.GloveBox.items, "True_Moozic_BHi.CassetteABBADancingQueen1976")
        table.insert(VehicleDistributions.GloveBox.items, 1 * _multVehicle)
        table.insert(VehicleDistributions.GloveBox.items, "True_Moozic_BHi.CassetteACDCBackInBlack1980")
        table.insert(VehicleDistributions.GloveBox.items, 1 * _multVehicle)
        table.insert(VehicleDistributions.GloveBox.items, "True_Moozic_BHi.CassetteAlabamaSongoftheSouth1988")
        table.insert(VehicleDistributions.GloveBox.items, 1 * _multVehicle)
        table.insert(VehicleDistributions.GloveBox.items, "True_Moozic_BHi.CassetteAmericaAHorseWithNoName1972")
        table.insert(VehicleDistributions.GloveBox.items, 1 * _multVehicle)
        table.insert(VehicleDistributions.GloveBox.items, "True_Moozic_BHi.CassetteAmericaSisterGoldenHair1975")
        table.insert(VehicleDistributions.GloveBox.items, 1 * _multVehicle)
        table.insert(VehicleDistributions.GloveBox.items, "True_Moozic_BHi.CassetteArvoPartSpiegelImSpiegel1978")
        table.insert(VehicleDistributions.GloveBox.items, 1 * _multVehicle)
        table.insert(VehicleDistributions.GloveBox.items, "True_Moozic_BHi.CassetteBeGoodTanyasDogsongakaSleepDogLu")
        table.insert(VehicleDistributions.GloveBox.items, 1 * _multVehicle)
        table.insert(VehicleDistributions.GloveBox.items, "True_Moozic_BHi.CassetteBeGoodTanyasUpAgainstTheWall2011")
        table.insert(VehicleDistributions.GloveBox.items, 1 * _multVehicle)
        table.insert(VehicleDistributions.GloveBox.items, "True_Moozic_BHi.CassetteBeastieBoysIntergalactic1998")
        table.insert(VehicleDistributions.GloveBox.items, 1 * _multVehicle)
        table.insert(VehicleDistributions.GloveBox.items, "True_Moozic_BHi.CassetteBeastieBoysSabotage1994")
        table.insert(VehicleDistributions.GloveBox.items, 1 * _multVehicle)
        table.insert(VehicleDistributions.GloveBox.items, "True_Moozic_BHi.CassetteBeeGeesMoreThanAWoman1977")
        table.insert(VehicleDistributions.GloveBox.items, 1 * _multVehicle)
        table.insert(VehicleDistributions.GloveBox.items, "True_Moozic_BHi.CassetteBillyIdolDancingwithmyself1980")
        table.insert(VehicleDistributions.GloveBox.items, 1 * _multVehicle)
        table.insert(VehicleDistributions.GloveBox.items, "True_Moozic_BHi.CassetteBillyJoelPianoMan1973")
        table.insert(VehicleDistributions.GloveBox.items, 1 * _multVehicle)
        table.insert(VehicleDistributions.GloveBox.items, "True_Moozic_BHi.CassetteBillyJoelUptownGirl1983")
        table.insert(VehicleDistributions.GloveBox.items, 1 * _multVehicle)
        table.insert(VehicleDistributions.GloveBox.items, "True_Moozic_BHi.CassetteBlondieHeartOfGlass1979")
        table.insert(VehicleDistributions.GloveBox.items, 1 * _multVehicle)
        table.insert(VehicleDistributions.GloveBox.items, "True_Moozic_BHi.CassetteBobDylanHighway61Revisited1965")
        table.insert(VehicleDistributions.GloveBox.items, 1 * _multVehicle)
        table.insert(VehicleDistributions.GloveBox.items, "True_Moozic_BHi.CassetteBobDylanJustLikeTomThumbsBlues19")
        table.insert(VehicleDistributions.GloveBox.items, 1 * _multVehicle)
        table.insert(VehicleDistributions.GloveBox.items, "True_Moozic_BHi.CassetteBobDylanLastThoughtsOnWoodyGuthr")
        table.insert(VehicleDistributions.GloveBox.items, 1 * _multVehicle)
        table.insert(VehicleDistributions.GloveBox.items, "True_Moozic_BHi.CassetteBobDylanVisionsOfJohanna1966")
        table.insert(VehicleDistributions.GloveBox.items, 1 * _multVehicle)
        table.insert(VehicleDistributions.GloveBox.items, "True_Moozic_BHi.CassetteBobMarleyTheWailersJamming1977")
        table.insert(VehicleDistributions.GloveBox.items, 1 * _multVehicle)
        table.insert(VehicleDistributions.GloveBox.items, "True_Moozic_BHi.CassetteBobMarleyTheWailersRedemptionSon")
        table.insert(VehicleDistributions.GloveBox.items, 1 * _multVehicle)
        table.insert(VehicleDistributions.GloveBox.items, "True_Moozic_BHi.CassetteBobMarleyTheWailersThreeLittleBi")
        table.insert(VehicleDistributions.GloveBox.items, 1 * _multVehicle)
        table.insert(VehicleDistributions.GloveBox.items, "True_Moozic_BHi.CassetteBobbyMcFerrinDontWorryBeHappy198")
        table.insert(VehicleDistributions.GloveBox.items, 1 * _multVehicle)
        table.insert(VehicleDistributions.GloveBox.items, "True_Moozic_BHi.CassetteBonJoviLivinOnAPrayer1986")
        table.insert(VehicleDistributions.GloveBox.items, 1 * _multVehicle)
        table.insert(VehicleDistributions.GloveBox.items, "True_Moozic_BHi.CassetteBoneyMGattagohome1979")
        table.insert(VehicleDistributions.GloveBox.items, 1 * _multVehicle)
        table.insert(VehicleDistributions.GloveBox.items, "True_Moozic_BHi.CassetteBoyzIIMenMotownphilly1991")
        table.insert(VehicleDistributions.GloveBox.items, 1 * _multVehicle)
        table.insert(VehicleDistributions.GloveBox.items, "True_Moozic_BHi.CassetteBruceHornsbyTheWayItIs1986")
        table.insert(VehicleDistributions.GloveBox.items, 1 * _multVehicle)
        table.insert(VehicleDistributions.GloveBox.items, "True_Moozic_BHi.CassetteBryanAdamsSummerOf691984")
        table.insert(VehicleDistributions.GloveBox.items, 1 * _multVehicle)
        table.insert(VehicleDistributions.GloveBox.items, "True_Moozic_BHi.CassetteChumbawambaTubthumping1997")
        table.insert(VehicleDistributions.GloveBox.items, 1 * _multVehicle)
        table.insert(VehicleDistributions.GloveBox.items, "True_Moozic_BHi.CassetteClashRocktheCasbah1982")
        table.insert(VehicleDistributions.GloveBox.items, 1 * _multVehicle)
        table.insert(VehicleDistributions.GloveBox.items, "True_Moozic_BHi.CassetteCoolioGangstasParadise1995")
        table.insert(VehicleDistributions.GloveBox.items, 1 * _multVehicle)
        table.insert(VehicleDistributions.GloveBox.items, "True_Moozic_BHi.CassetteCreedenceClearwaterRevivalFortun")
        table.insert(VehicleDistributions.GloveBox.items, 1 * _multVehicle)
        table.insert(VehicleDistributions.GloveBox.items, "True_Moozic_BHi.CassetteCreedenceClearwaterRevivalHaveYo")
        table.insert(VehicleDistributions.GloveBox.items, 1 * _multVehicle)
        table.insert(VehicleDistributions.GloveBox.items, "True_Moozic_BHi.CassetteCultureClubKarmaChameleon1983")
        table.insert(VehicleDistributions.GloveBox.items, 1 * _multVehicle)
        table.insert(VehicleDistributions.GloveBox.items, "True_Moozic_BHi.CassetteCyndiLauperAllThroughTheNight198")
        table.insert(VehicleDistributions.GloveBox.items, 1 * _multVehicle)
        table.insert(VehicleDistributions.GloveBox.items, "True_Moozic_BHi.CassetteCyndiLauperGirlsJustWantToHaveFu")
        table.insert(VehicleDistributions.GloveBox.items, 1 * _multVehicle)
        table.insert(VehicleDistributions.GloveBox.items, "True_Moozic_BHi.CassetteCyndiLauperHeyNowGirlsJustWantTo")
        table.insert(VehicleDistributions.GloveBox.items, 1 * _multVehicle)
        table.insert(VehicleDistributions.GloveBox.items, "True_Moozic_BHi.CassetteCyndiLauperIDroveAllNight1989")
        table.insert(VehicleDistributions.GloveBox.items, 1 * _multVehicle)
        table.insert(VehicleDistributions.GloveBox.items, "True_Moozic_BHi.CassetteCyndiLauperSheBop1983")
        table.insert(VehicleDistributions.GloveBox.items, 1 * _multVehicle)
        table.insert(VehicleDistributions.GloveBox.items, "True_Moozic_BHi.CassetteCyndiLauperTheGooniesRGoodEnough")
        table.insert(VehicleDistributions.GloveBox.items, 1 * _multVehicle)
        table.insert(VehicleDistributions.GloveBox.items, "True_Moozic_BHi.CassetteCyndiLauperWhenYouWereMine1985")
        table.insert(VehicleDistributions.GloveBox.items, 1 * _multVehicle)
        table.insert(VehicleDistributions.GloveBox.items, "True_Moozic_BHi.CassetteDarylHallJohnOatesManeater1982")
        table.insert(VehicleDistributions.GloveBox.items, 1 * _multVehicle)
        table.insert(VehicleDistributions.GloveBox.items, "True_Moozic_BHi.CassetteDavidBowieSpaceOddity1969")
        table.insert(VehicleDistributions.GloveBox.items, 1 * _multVehicle)
        table.insert(VehicleDistributions.GloveBox.items, "True_Moozic_BHi.CassetteDavidBowieQueenUnderPressure1981")
        table.insert(VehicleDistributions.GloveBox.items, 1 * _multVehicle)
        table.insert(VehicleDistributions.GloveBox.items, "True_Moozic_BHi.CassetteDavidBowieSuffragetteCity1972")
        table.insert(VehicleDistributions.GloveBox.items, 1 * _multVehicle)
        table.insert(VehicleDistributions.GloveBox.items, "True_Moozic_BHi.CassetteDavidBowieThemanwhosoldtheworld1")
        table.insert(VehicleDistributions.GloveBox.items, 1 * _multVehicle)
        table.insert(VehicleDistributions.GloveBox.items, "True_Moozic_BHi.CassetteDevoWhipIt1980")
        table.insert(VehicleDistributions.GloveBox.items, 1 * _multVehicle)
        table.insert(VehicleDistributions.GloveBox.items, "True_Moozic_BHi.CassetteDonMcleanAmericanPie1971")
        table.insert(VehicleDistributions.GloveBox.items, 1 * _multVehicle)
        table.insert(VehicleDistributions.GloveBox.items, "True_Moozic_BHi.CassetteEaglesHotelCalifornia1977")
        table.insert(VehicleDistributions.GloveBox.items, 1 * _multVehicle)
        table.insert(VehicleDistributions.GloveBox.items, "True_Moozic_BHi.CassetteELOMrBlueSky1977")
        table.insert(VehicleDistributions.GloveBox.items, 1 * _multVehicle)
        table.insert(VehicleDistributions.GloveBox.items, "True_Moozic_BHi.CassetteEltonJohnRocketMan1972")
        table.insert(VehicleDistributions.GloveBox.items, 1 * _multVehicle)
        table.insert(VehicleDistributions.GloveBox.items, "True_Moozic_BHi.CassetteEuropeTheFinalCountdown1986")
        table.insert(VehicleDistributions.GloveBox.items, 1 * _multVehicle)
        table.insert(VehicleDistributions.GloveBox.items, "True_Moozic_BHi.CassetteGaryNumanCars1979")
        table.insert(VehicleDistributions.GloveBox.items, 1 * _multVehicle)
        table.insert(VehicleDistributions.GloveBox.items, "True_Moozic_BHi.CassetteGershonKingsleyPopcorn1969")
        table.insert(VehicleDistributions.GloveBox.items, 1 * _multVehicle)
        table.insert(VehicleDistributions.GloveBox.items, "True_Moozic_BHi.CassetteGunsNRosesWelcomeToTheJungle1987")
        table.insert(VehicleDistributions.GloveBox.items, 1 * _multVehicle)
        table.insert(VehicleDistributions.GloveBox.items, "True_Moozic_BHi.CassetteHouseofPainJumpAround1992")
        table.insert(VehicleDistributions.GloveBox.items, 1 * _multVehicle)
        table.insert(VehicleDistributions.GloveBox.items, "True_Moozic_BHi.CassetteJimCroceTimeInABottle1972")
        table.insert(VehicleDistributions.GloveBox.items, 1 * _multVehicle)
        table.insert(VehicleDistributions.GloveBox.items, "True_Moozic_BHi.CassetteKansasDustintheWind1977")
        table.insert(VehicleDistributions.GloveBox.items, 1 * _multVehicle)
        table.insert(VehicleDistributions.GloveBox.items, "True_Moozic_BHi.CassetteKennyLogginsDangerZone1986")
        table.insert(VehicleDistributions.GloveBox.items, 1 * _multVehicle)
        table.insert(VehicleDistributions.GloveBox.items, "True_Moozic_BHi.CassetteKraftwerkPocketCalculator1981")
        table.insert(VehicleDistributions.GloveBox.items, 1 * _multVehicle)
        table.insert(VehicleDistributions.GloveBox.items, "True_Moozic_BHi.CassetteLaurieAndersonOSuperman1981")
        table.insert(VehicleDistributions.GloveBox.items, 1 * _multVehicle)
        table.insert(VehicleDistributions.GloveBox.items, "True_Moozic_BHi.CassetteLeonardCohenFamousBlueRaincoat19")
        table.insert(VehicleDistributions.GloveBox.items, 1 * _multVehicle)
        table.insert(VehicleDistributions.GloveBox.items, "True_Moozic_BHi.CassetteLLCOOLJMamaSaidKnockYouOut1990")
        table.insert(VehicleDistributions.GloveBox.items, 1 * _multVehicle)
        table.insert(VehicleDistributions.GloveBox.items, "True_Moozic_BHi.CassetteLouReedPerfectDay1972")
        table.insert(VehicleDistributions.GloveBox.items, 1 * _multVehicle)
        table.insert(VehicleDistributions.GloveBox.items, "True_Moozic_BHi.CassetteLouReedWalkontheWildSide1972")
        table.insert(VehicleDistributions.GloveBox.items, 1 * _multVehicle)
        table.insert(VehicleDistributions.GloveBox.items, "True_Moozic_BHi.CassetteLoverboyWorkingfortheWeekend1981")
        table.insert(VehicleDistributions.GloveBox.items, 1 * _multVehicle)
        table.insert(VehicleDistributions.GloveBox.items, "True_Moozic_BHi.CassetteLynrydSkynyrdSweetHomeAlabama197")
        table.insert(VehicleDistributions.GloveBox.items, 1 * _multVehicle)
        table.insert(VehicleDistributions.GloveBox.items, "True_Moozic_BHi.CassetteMadonnaLikeAVirgin1984")
        table.insert(VehicleDistributions.GloveBox.items, 1 * _multVehicle)
        table.insert(VehicleDistributions.GloveBox.items, "True_Moozic_BHi.CassetteMatthewWilderBreakMyStride1983")
        table.insert(VehicleDistributions.GloveBox.items, 1 * _multVehicle)
        table.insert(VehicleDistributions.GloveBox.items, "True_Moozic_BHi.CassetteMCHammerUCantTouchThis1990")
        table.insert(VehicleDistributions.GloveBox.items, 1 * _multVehicle)
        table.insert(VehicleDistributions.GloveBox.items, "True_Moozic_BHi.CassetteMichaelJacksonBeatIt1982")
        table.insert(VehicleDistributions.GloveBox.items, 1 * _multVehicle)
        table.insert(VehicleDistributions.GloveBox.items, "True_Moozic_BHi.CassetteMichaelJacksonThriller1983")
        table.insert(VehicleDistributions.GloveBox.items, 1 * _multVehicle)
        table.insert(VehicleDistributions.GloveBox.items, "True_Moozic_BHi.CassetteMotorheadAceOfSpades1980")
        table.insert(VehicleDistributions.GloveBox.items, 1 * _multVehicle)
        table.insert(VehicleDistributions.GloveBox.items, "True_Moozic_BHi.CassetteNatalieImbrugliaTorn1997")
        table.insert(VehicleDistributions.GloveBox.items, 1 * _multVehicle)
        table.insert(VehicleDistributions.GloveBox.items, "True_Moozic_BHi.CassetteNaughtyByNatureOPP1991")
        table.insert(VehicleDistributions.GloveBox.items, 1 * _multVehicle)
        table.insert(VehicleDistributions.GloveBox.items, "True_Moozic_BHi.CassetteNeilYoungCinnamonGirl1969")
        table.insert(VehicleDistributions.GloveBox.items, 1 * _multVehicle)
        table.insert(VehicleDistributions.GloveBox.items, "True_Moozic_BHi.CassetteNeilYoungCowgirlInTheSand1969")
        table.insert(VehicleDistributions.GloveBox.items, 1 * _multVehicle)
        table.insert(VehicleDistributions.GloveBox.items, "True_Moozic_BHi.CassetteNENA99RedBalloons1984")
        table.insert(VehicleDistributions.GloveBox.items, 1 * _multVehicle)
        table.insert(VehicleDistributions.GloveBox.items, "True_Moozic_BHi.CassettePinkFloydComfortablyNumb1980")
        table.insert(VehicleDistributions.GloveBox.items, 1 * _multVehicle)
        table.insert(VehicleDistributions.GloveBox.items, "True_Moozic_BHi.CassetteQueenAnotherOneBitestheDust1980")
        table.insert(VehicleDistributions.GloveBox.items, 1 * _multVehicle)
        table.insert(VehicleDistributions.GloveBox.items, "True_Moozic_BHi.CassetteQueenBohemianRhapsody1975")
        table.insert(VehicleDistributions.GloveBox.items, 1 * _multVehicle)
        table.insert(VehicleDistributions.GloveBox.items, "True_Moozic_BHi.CassetteRedboneComeandGetYourLove1973")
        table.insert(VehicleDistributions.GloveBox.items, 1 * _multVehicle)
        table.insert(VehicleDistributions.GloveBox.items, "True_Moozic_BHi.CassetteREOSpeedwagonCantFightThisFeelin")
        table.insert(VehicleDistributions.GloveBox.items, 1 * _multVehicle)
        table.insert(VehicleDistributions.GloveBox.items, "True_Moozic_BHi.CassetteRickAstleyNeverGonnaGiveYouUp198")
        table.insert(VehicleDistributions.GloveBox.items, 1 * _multVehicle)
        table.insert(VehicleDistributions.GloveBox.items, "True_Moozic_BHi.CassetteRollingStonesPaintItBlack1966")
        table.insert(VehicleDistributions.GloveBox.items, 1 * _multVehicle)
        table.insert(VehicleDistributions.GloveBox.items, "True_Moozic_BHi.CassetteSaltNPepaShoop1993")
        table.insert(VehicleDistributions.GloveBox.items, 1 * _multVehicle)
        table.insert(VehicleDistributions.GloveBox.items, "True_Moozic_BHi.CassetteScatmanskibabopbadopbop1995")
        table.insert(VehicleDistributions.GloveBox.items, 1 * _multVehicle)
        table.insert(VehicleDistributions.GloveBox.items, "True_Moozic_BHi.CassetteSimonGarfunkelCecilia1970")
        table.insert(VehicleDistributions.GloveBox.items, 1 * _multVehicle)
        table.insert(VehicleDistributions.GloveBox.items, "True_Moozic_BHi.CassetteSimonGarfunkelMrsRobinson1968")
        table.insert(VehicleDistributions.GloveBox.items, 1 * _multVehicle)
        table.insert(VehicleDistributions.GloveBox.items, "True_Moozic_BHi.CassetteSineadOConnorNothingCompares2U19")
        table.insert(VehicleDistributions.GloveBox.items, 1 * _multVehicle)
        table.insert(VehicleDistributions.GloveBox.items, "True_Moozic_BHi.CassetteSirMixALotBabyGotBack1992")
        table.insert(VehicleDistributions.GloveBox.items, 1 * _multVehicle)
        table.insert(VehicleDistributions.GloveBox.items, "True_Moozic_BHi.CassetteStarshipNothingsGonnaStopUsNow19")
        table.insert(VehicleDistributions.GloveBox.items, 1 * _multVehicle)
        table.insert(VehicleDistributions.GloveBox.items, "True_Moozic_BHi.CassetteSteveEarleColoradoGirl2009")
        table.insert(VehicleDistributions.GloveBox.items, 1 * _multVehicle)
        table.insert(VehicleDistributions.GloveBox.items, "True_Moozic_BHi.CassetteSteveEarleLoretta2009")
        table.insert(VehicleDistributions.GloveBox.items, 1 * _multVehicle)
        table.insert(VehicleDistributions.GloveBox.items, "True_Moozic_BHi.CassetteSteveEarleWhiteFreightlinerBlues")
        table.insert(VehicleDistributions.GloveBox.items, 1 * _multVehicle)
        table.insert(VehicleDistributions.GloveBox.items, "True_Moozic_BHi.CassetteTacoPuttinOnTheRitz1982")
        table.insert(VehicleDistributions.GloveBox.items, 1 * _multVehicle)
        table.insert(VehicleDistributions.GloveBox.items, "True_Moozic_BHi.CassetteTalkingHeadsOnceinaLifetime1980")
        table.insert(VehicleDistributions.GloveBox.items, 1 * _multVehicle)
        table.insert(VehicleDistributions.GloveBox.items, "True_Moozic_BHi.CassetteTalkingHeadsPsychoKiller1977")
        table.insert(VehicleDistributions.GloveBox.items, 1 * _multVehicle)
        table.insert(VehicleDistributions.GloveBox.items, "True_Moozic_BHi.CassetteTearsforFearsEverybodyWantstoRul")
        table.insert(VehicleDistributions.GloveBox.items, 1 * _multVehicle)
        table.insert(VehicleDistributions.GloveBox.items, "True_Moozic_BHi.CassetteTechnoSyndromeMortalKombat1994")
        table.insert(VehicleDistributions.GloveBox.items, 1 * _multVehicle)
        table.insert(VehicleDistributions.GloveBox.items, "True_Moozic_BHi.CassetteTechnotronicPumpUpTheJam1989")
        table.insert(VehicleDistributions.GloveBox.items, 1 * _multVehicle)
        table.insert(VehicleDistributions.GloveBox.items, "True_Moozic_BHi.CassetteTheAnimalsHouseoftheRisingSun196")
        table.insert(VehicleDistributions.GloveBox.items, 1 * _multVehicle)
        table.insert(VehicleDistributions.GloveBox.items, "True_Moozic_BHi.CassetteTheBeachBoysKokomo1988")
        table.insert(VehicleDistributions.GloveBox.items, 1 * _multVehicle)
        table.insert(VehicleDistributions.GloveBox.items, "True_Moozic_BHi.CassetteTheBugglesVideoKilledtheRadioSta")
        table.insert(VehicleDistributions.GloveBox.items, 1 * _multVehicle)
        table.insert(VehicleDistributions.GloveBox.items, "True_Moozic_BHi.CassetteTheLastofUs2013")
        table.insert(VehicleDistributions.GloveBox.items, 1 * _multVehicle)
        table.insert(VehicleDistributions.GloveBox.items, "True_Moozic_BHi.CassetteTheOhHellosSoldierPoetKing2015")
        table.insert(VehicleDistributions.GloveBox.items, 1 * _multVehicle)
        table.insert(VehicleDistributions.GloveBox.items, "True_Moozic_BHi.CassetteThePoliceEverybreathyoutake1983")
        table.insert(VehicleDistributions.GloveBox.items, 1 * _multVehicle)
        table.insert(VehicleDistributions.GloveBox.items, "True_Moozic_BHi.CassetteThePoliceRoxanne1979")
        table.insert(VehicleDistributions.GloveBox.items, 1 * _multVehicle)
        table.insert(VehicleDistributions.GloveBox.items, "True_Moozic_BHi.CassetteTheProdigyBreathe1996")
        table.insert(VehicleDistributions.GloveBox.items, 1 * _multVehicle)
        table.insert(VehicleDistributions.GloveBox.items, "True_Moozic_BHi.CassetteTheShinsNewSlang2001")
        table.insert(VehicleDistributions.GloveBox.items, 1 * _multVehicle)
        table.insert(VehicleDistributions.GloveBox.items, "True_Moozic_BHi.CassetteTheStranglersGoldenBrown1981")
        table.insert(VehicleDistributions.GloveBox.items, 1 * _multVehicle)
        table.insert(VehicleDistributions.GloveBox.items, "True_Moozic_BHi.CassetteTheVerveBitterSweetSymphony1997")
        table.insert(VehicleDistributions.GloveBox.items, 1 * _multVehicle)
        table.insert(VehicleDistributions.GloveBox.items, "True_Moozic_BHi.CassetteTiffanyIThinkWereAloneNow1987")
        table.insert(VehicleDistributions.GloveBox.items, 1 * _multVehicle)
        table.insert(VehicleDistributions.GloveBox.items, "True_Moozic_BHi.CassetteTomPettyFreeFalling1988")
        table.insert(VehicleDistributions.GloveBox.items, 1 * _multVehicle)
        table.insert(VehicleDistributions.GloveBox.items, "True_Moozic_BHi.CassetteToneLocFunkyColdMedina1989")
        table.insert(VehicleDistributions.GloveBox.items, 1 * _multVehicle)
        table.insert(VehicleDistributions.GloveBox.items, "True_Moozic_BHi.CassetteTwistedSisterWereNotGonnaTakeIt1")
        table.insert(VehicleDistributions.GloveBox.items, 1 * _multVehicle)
        table.insert(VehicleDistributions.GloveBox.items, "True_Moozic_BHi.CassetteVanillaIceIceIceBaby1990")
        table.insert(VehicleDistributions.GloveBox.items, 1 * _multVehicle)
    end
    if VehicleDistributions and VehicleDistributions.Trunk then
        table.insert(VehicleDistributions.Trunk.items, "True_Moozic_BHi.CassetteAFlockOfSeagullsIRanSoFarAway198")
        table.insert(VehicleDistributions.Trunk.items, 0.5 * _multVehicle)
        table.insert(VehicleDistributions.Trunk.items, "True_Moozic_BHi.CassetteATribeCalledQuestCanIKickIt1990")
        table.insert(VehicleDistributions.Trunk.items, 0.5 * _multVehicle)
        table.insert(VehicleDistributions.Trunk.items, "True_Moozic_BHi.CassetteAHaTakeOnMe1985")
        table.insert(VehicleDistributions.Trunk.items, 0.5 * _multVehicle)
        table.insert(VehicleDistributions.Trunk.items, "True_Moozic_BHi.CassetteABBADancingQueen1976")
        table.insert(VehicleDistributions.Trunk.items, 0.5 * _multVehicle)
        table.insert(VehicleDistributions.Trunk.items, "True_Moozic_BHi.CassetteACDCBackInBlack1980")
        table.insert(VehicleDistributions.Trunk.items, 0.5 * _multVehicle)
        table.insert(VehicleDistributions.Trunk.items, "True_Moozic_BHi.CassetteAlabamaSongoftheSouth1988")
        table.insert(VehicleDistributions.Trunk.items, 0.5 * _multVehicle)
        table.insert(VehicleDistributions.Trunk.items, "True_Moozic_BHi.CassetteAmericaAHorseWithNoName1972")
        table.insert(VehicleDistributions.Trunk.items, 0.5 * _multVehicle)
        table.insert(VehicleDistributions.Trunk.items, "True_Moozic_BHi.CassetteAmericaSisterGoldenHair1975")
        table.insert(VehicleDistributions.Trunk.items, 0.5 * _multVehicle)
        table.insert(VehicleDistributions.Trunk.items, "True_Moozic_BHi.CassetteArvoPartSpiegelImSpiegel1978")
        table.insert(VehicleDistributions.Trunk.items, 0.5 * _multVehicle)
        table.insert(VehicleDistributions.Trunk.items, "True_Moozic_BHi.CassetteBeGoodTanyasDogsongakaSleepDogLu")
        table.insert(VehicleDistributions.Trunk.items, 0.5 * _multVehicle)
        table.insert(VehicleDistributions.Trunk.items, "True_Moozic_BHi.CassetteBeGoodTanyasUpAgainstTheWall2011")
        table.insert(VehicleDistributions.Trunk.items, 0.5 * _multVehicle)
        table.insert(VehicleDistributions.Trunk.items, "True_Moozic_BHi.CassetteBeastieBoysIntergalactic1998")
        table.insert(VehicleDistributions.Trunk.items, 0.5 * _multVehicle)
        table.insert(VehicleDistributions.Trunk.items, "True_Moozic_BHi.CassetteBeastieBoysSabotage1994")
        table.insert(VehicleDistributions.Trunk.items, 0.5 * _multVehicle)
        table.insert(VehicleDistributions.Trunk.items, "True_Moozic_BHi.CassetteBeeGeesMoreThanAWoman1977")
        table.insert(VehicleDistributions.Trunk.items, 0.5 * _multVehicle)
        table.insert(VehicleDistributions.Trunk.items, "True_Moozic_BHi.CassetteBillyIdolDancingwithmyself1980")
        table.insert(VehicleDistributions.Trunk.items, 0.5 * _multVehicle)
        table.insert(VehicleDistributions.Trunk.items, "True_Moozic_BHi.CassetteBillyJoelPianoMan1973")
        table.insert(VehicleDistributions.Trunk.items, 0.5 * _multVehicle)
        table.insert(VehicleDistributions.Trunk.items, "True_Moozic_BHi.CassetteBillyJoelUptownGirl1983")
        table.insert(VehicleDistributions.Trunk.items, 0.5 * _multVehicle)
        table.insert(VehicleDistributions.Trunk.items, "True_Moozic_BHi.CassetteBlondieHeartOfGlass1979")
        table.insert(VehicleDistributions.Trunk.items, 0.5 * _multVehicle)
        table.insert(VehicleDistributions.Trunk.items, "True_Moozic_BHi.CassetteBobDylanHighway61Revisited1965")
        table.insert(VehicleDistributions.Trunk.items, 0.5 * _multVehicle)
        table.insert(VehicleDistributions.Trunk.items, "True_Moozic_BHi.CassetteBobDylanJustLikeTomThumbsBlues19")
        table.insert(VehicleDistributions.Trunk.items, 0.5 * _multVehicle)
        table.insert(VehicleDistributions.Trunk.items, "True_Moozic_BHi.CassetteBobDylanLastThoughtsOnWoodyGuthr")
        table.insert(VehicleDistributions.Trunk.items, 0.5 * _multVehicle)
        table.insert(VehicleDistributions.Trunk.items, "True_Moozic_BHi.CassetteBobDylanVisionsOfJohanna1966")
        table.insert(VehicleDistributions.Trunk.items, 0.5 * _multVehicle)
        table.insert(VehicleDistributions.Trunk.items, "True_Moozic_BHi.CassetteBobMarleyTheWailersJamming1977")
        table.insert(VehicleDistributions.Trunk.items, 0.5 * _multVehicle)
        table.insert(VehicleDistributions.Trunk.items, "True_Moozic_BHi.CassetteBobMarleyTheWailersRedemptionSon")
        table.insert(VehicleDistributions.Trunk.items, 0.5 * _multVehicle)
        table.insert(VehicleDistributions.Trunk.items, "True_Moozic_BHi.CassetteBobMarleyTheWailersThreeLittleBi")
        table.insert(VehicleDistributions.Trunk.items, 0.5 * _multVehicle)
        table.insert(VehicleDistributions.Trunk.items, "True_Moozic_BHi.CassetteBobbyMcFerrinDontWorryBeHappy198")
        table.insert(VehicleDistributions.Trunk.items, 0.5 * _multVehicle)
        table.insert(VehicleDistributions.Trunk.items, "True_Moozic_BHi.CassetteBonJoviLivinOnAPrayer1986")
        table.insert(VehicleDistributions.Trunk.items, 0.5 * _multVehicle)
        table.insert(VehicleDistributions.Trunk.items, "True_Moozic_BHi.CassetteBoneyMGattagohome1979")
        table.insert(VehicleDistributions.Trunk.items, 0.5 * _multVehicle)
        table.insert(VehicleDistributions.Trunk.items, "True_Moozic_BHi.CassetteBoyzIIMenMotownphilly1991")
        table.insert(VehicleDistributions.Trunk.items, 0.5 * _multVehicle)
        table.insert(VehicleDistributions.Trunk.items, "True_Moozic_BHi.CassetteBruceHornsbyTheWayItIs1986")
        table.insert(VehicleDistributions.Trunk.items, 0.5 * _multVehicle)
        table.insert(VehicleDistributions.Trunk.items, "True_Moozic_BHi.CassetteBryanAdamsSummerOf691984")
        table.insert(VehicleDistributions.Trunk.items, 0.5 * _multVehicle)
        table.insert(VehicleDistributions.Trunk.items, "True_Moozic_BHi.CassetteChumbawambaTubthumping1997")
        table.insert(VehicleDistributions.Trunk.items, 0.5 * _multVehicle)
        table.insert(VehicleDistributions.Trunk.items, "True_Moozic_BHi.CassetteClashRocktheCasbah1982")
        table.insert(VehicleDistributions.Trunk.items, 0.5 * _multVehicle)
        table.insert(VehicleDistributions.Trunk.items, "True_Moozic_BHi.CassetteCoolioGangstasParadise1995")
        table.insert(VehicleDistributions.Trunk.items, 0.5 * _multVehicle)
        table.insert(VehicleDistributions.Trunk.items, "True_Moozic_BHi.CassetteCreedenceClearwaterRevivalFortun")
        table.insert(VehicleDistributions.Trunk.items, 0.5 * _multVehicle)
        table.insert(VehicleDistributions.Trunk.items, "True_Moozic_BHi.CassetteCreedenceClearwaterRevivalHaveYo")
        table.insert(VehicleDistributions.Trunk.items, 0.5 * _multVehicle)
        table.insert(VehicleDistributions.Trunk.items, "True_Moozic_BHi.CassetteCultureClubKarmaChameleon1983")
        table.insert(VehicleDistributions.Trunk.items, 0.5 * _multVehicle)
        table.insert(VehicleDistributions.Trunk.items, "True_Moozic_BHi.CassetteCyndiLauperAllThroughTheNight198")
        table.insert(VehicleDistributions.Trunk.items, 0.5 * _multVehicle)
        table.insert(VehicleDistributions.Trunk.items, "True_Moozic_BHi.CassetteCyndiLauperGirlsJustWantToHaveFu")
        table.insert(VehicleDistributions.Trunk.items, 0.5 * _multVehicle)
        table.insert(VehicleDistributions.Trunk.items, "True_Moozic_BHi.CassetteCyndiLauperHeyNowGirlsJustWantTo")
        table.insert(VehicleDistributions.Trunk.items, 0.5 * _multVehicle)
        table.insert(VehicleDistributions.Trunk.items, "True_Moozic_BHi.CassetteCyndiLauperIDroveAllNight1989")
        table.insert(VehicleDistributions.Trunk.items, 0.5 * _multVehicle)
        table.insert(VehicleDistributions.Trunk.items, "True_Moozic_BHi.CassetteCyndiLauperSheBop1983")
        table.insert(VehicleDistributions.Trunk.items, 0.5 * _multVehicle)
        table.insert(VehicleDistributions.Trunk.items, "True_Moozic_BHi.CassetteCyndiLauperTheGooniesRGoodEnough")
        table.insert(VehicleDistributions.Trunk.items, 0.5 * _multVehicle)
        table.insert(VehicleDistributions.Trunk.items, "True_Moozic_BHi.CassetteCyndiLauperWhenYouWereMine1985")
        table.insert(VehicleDistributions.Trunk.items, 0.5 * _multVehicle)
        table.insert(VehicleDistributions.Trunk.items, "True_Moozic_BHi.CassetteDarylHallJohnOatesManeater1982")
        table.insert(VehicleDistributions.Trunk.items, 0.5 * _multVehicle)
        table.insert(VehicleDistributions.Trunk.items, "True_Moozic_BHi.CassetteDavidBowieSpaceOddity1969")
        table.insert(VehicleDistributions.Trunk.items, 0.5 * _multVehicle)
        table.insert(VehicleDistributions.Trunk.items, "True_Moozic_BHi.CassetteDavidBowieQueenUnderPressure1981")
        table.insert(VehicleDistributions.Trunk.items, 0.5 * _multVehicle)
        table.insert(VehicleDistributions.Trunk.items, "True_Moozic_BHi.CassetteDavidBowieSuffragetteCity1972")
        table.insert(VehicleDistributions.Trunk.items, 0.5 * _multVehicle)
        table.insert(VehicleDistributions.Trunk.items, "True_Moozic_BHi.CassetteDavidBowieThemanwhosoldtheworld1")
        table.insert(VehicleDistributions.Trunk.items, 0.5 * _multVehicle)
        table.insert(VehicleDistributions.Trunk.items, "True_Moozic_BHi.CassetteDevoWhipIt1980")
        table.insert(VehicleDistributions.Trunk.items, 0.5 * _multVehicle)
        table.insert(VehicleDistributions.Trunk.items, "True_Moozic_BHi.CassetteDonMcleanAmericanPie1971")
        table.insert(VehicleDistributions.Trunk.items, 0.5 * _multVehicle)
        table.insert(VehicleDistributions.Trunk.items, "True_Moozic_BHi.CassetteEaglesHotelCalifornia1977")
        table.insert(VehicleDistributions.Trunk.items, 0.5 * _multVehicle)
        table.insert(VehicleDistributions.Trunk.items, "True_Moozic_BHi.CassetteELOMrBlueSky1977")
        table.insert(VehicleDistributions.Trunk.items, 0.5 * _multVehicle)
        table.insert(VehicleDistributions.Trunk.items, "True_Moozic_BHi.CassetteEltonJohnRocketMan1972")
        table.insert(VehicleDistributions.Trunk.items, 0.5 * _multVehicle)
        table.insert(VehicleDistributions.Trunk.items, "True_Moozic_BHi.CassetteEuropeTheFinalCountdown1986")
        table.insert(VehicleDistributions.Trunk.items, 0.5 * _multVehicle)
        table.insert(VehicleDistributions.Trunk.items, "True_Moozic_BHi.CassetteGaryNumanCars1979")
        table.insert(VehicleDistributions.Trunk.items, 0.5 * _multVehicle)
        table.insert(VehicleDistributions.Trunk.items, "True_Moozic_BHi.CassetteGershonKingsleyPopcorn1969")
        table.insert(VehicleDistributions.Trunk.items, 0.5 * _multVehicle)
        table.insert(VehicleDistributions.Trunk.items, "True_Moozic_BHi.CassetteGunsNRosesWelcomeToTheJungle1987")
        table.insert(VehicleDistributions.Trunk.items, 0.5 * _multVehicle)
        table.insert(VehicleDistributions.Trunk.items, "True_Moozic_BHi.CassetteHouseofPainJumpAround1992")
        table.insert(VehicleDistributions.Trunk.items, 0.5 * _multVehicle)
        table.insert(VehicleDistributions.Trunk.items, "True_Moozic_BHi.CassetteJimCroceTimeInABottle1972")
        table.insert(VehicleDistributions.Trunk.items, 0.5 * _multVehicle)
        table.insert(VehicleDistributions.Trunk.items, "True_Moozic_BHi.CassetteKansasDustintheWind1977")
        table.insert(VehicleDistributions.Trunk.items, 0.5 * _multVehicle)
        table.insert(VehicleDistributions.Trunk.items, "True_Moozic_BHi.CassetteKennyLogginsDangerZone1986")
        table.insert(VehicleDistributions.Trunk.items, 0.5 * _multVehicle)
        table.insert(VehicleDistributions.Trunk.items, "True_Moozic_BHi.CassetteKraftwerkPocketCalculator1981")
        table.insert(VehicleDistributions.Trunk.items, 0.5 * _multVehicle)
        table.insert(VehicleDistributions.Trunk.items, "True_Moozic_BHi.CassetteLaurieAndersonOSuperman1981")
        table.insert(VehicleDistributions.Trunk.items, 0.5 * _multVehicle)
        table.insert(VehicleDistributions.Trunk.items, "True_Moozic_BHi.CassetteLeonardCohenFamousBlueRaincoat19")
        table.insert(VehicleDistributions.Trunk.items, 0.5 * _multVehicle)
        table.insert(VehicleDistributions.Trunk.items, "True_Moozic_BHi.CassetteLLCOOLJMamaSaidKnockYouOut1990")
        table.insert(VehicleDistributions.Trunk.items, 0.5 * _multVehicle)
        table.insert(VehicleDistributions.Trunk.items, "True_Moozic_BHi.CassetteLouReedPerfectDay1972")
        table.insert(VehicleDistributions.Trunk.items, 0.5 * _multVehicle)
        table.insert(VehicleDistributions.Trunk.items, "True_Moozic_BHi.CassetteLouReedWalkontheWildSide1972")
        table.insert(VehicleDistributions.Trunk.items, 0.5 * _multVehicle)
        table.insert(VehicleDistributions.Trunk.items, "True_Moozic_BHi.CassetteLoverboyWorkingfortheWeekend1981")
        table.insert(VehicleDistributions.Trunk.items, 0.5 * _multVehicle)
        table.insert(VehicleDistributions.Trunk.items, "True_Moozic_BHi.CassetteLynrydSkynyrdSweetHomeAlabama197")
        table.insert(VehicleDistributions.Trunk.items, 0.5 * _multVehicle)
        table.insert(VehicleDistributions.Trunk.items, "True_Moozic_BHi.CassetteMadonnaLikeAVirgin1984")
        table.insert(VehicleDistributions.Trunk.items, 0.5 * _multVehicle)
        table.insert(VehicleDistributions.Trunk.items, "True_Moozic_BHi.CassetteMatthewWilderBreakMyStride1983")
        table.insert(VehicleDistributions.Trunk.items, 0.5 * _multVehicle)
        table.insert(VehicleDistributions.Trunk.items, "True_Moozic_BHi.CassetteMCHammerUCantTouchThis1990")
        table.insert(VehicleDistributions.Trunk.items, 0.5 * _multVehicle)
        table.insert(VehicleDistributions.Trunk.items, "True_Moozic_BHi.CassetteMichaelJacksonBeatIt1982")
        table.insert(VehicleDistributions.Trunk.items, 0.5 * _multVehicle)
        table.insert(VehicleDistributions.Trunk.items, "True_Moozic_BHi.CassetteMichaelJacksonThriller1983")
        table.insert(VehicleDistributions.Trunk.items, 0.5 * _multVehicle)
        table.insert(VehicleDistributions.Trunk.items, "True_Moozic_BHi.CassetteMotorheadAceOfSpades1980")
        table.insert(VehicleDistributions.Trunk.items, 0.5 * _multVehicle)
        table.insert(VehicleDistributions.Trunk.items, "True_Moozic_BHi.CassetteNatalieImbrugliaTorn1997")
        table.insert(VehicleDistributions.Trunk.items, 0.5 * _multVehicle)
        table.insert(VehicleDistributions.Trunk.items, "True_Moozic_BHi.CassetteNaughtyByNatureOPP1991")
        table.insert(VehicleDistributions.Trunk.items, 0.5 * _multVehicle)
        table.insert(VehicleDistributions.Trunk.items, "True_Moozic_BHi.CassetteNeilYoungCinnamonGirl1969")
        table.insert(VehicleDistributions.Trunk.items, 0.5 * _multVehicle)
        table.insert(VehicleDistributions.Trunk.items, "True_Moozic_BHi.CassetteNeilYoungCowgirlInTheSand1969")
        table.insert(VehicleDistributions.Trunk.items, 0.5 * _multVehicle)
        table.insert(VehicleDistributions.Trunk.items, "True_Moozic_BHi.CassetteNENA99RedBalloons1984")
        table.insert(VehicleDistributions.Trunk.items, 0.5 * _multVehicle)
        table.insert(VehicleDistributions.Trunk.items, "True_Moozic_BHi.CassettePinkFloydComfortablyNumb1980")
        table.insert(VehicleDistributions.Trunk.items, 0.5 * _multVehicle)
        table.insert(VehicleDistributions.Trunk.items, "True_Moozic_BHi.CassetteQueenAnotherOneBitestheDust1980")
        table.insert(VehicleDistributions.Trunk.items, 0.5 * _multVehicle)
        table.insert(VehicleDistributions.Trunk.items, "True_Moozic_BHi.CassetteQueenBohemianRhapsody1975")
        table.insert(VehicleDistributions.Trunk.items, 0.5 * _multVehicle)
        table.insert(VehicleDistributions.Trunk.items, "True_Moozic_BHi.CassetteRedboneComeandGetYourLove1973")
        table.insert(VehicleDistributions.Trunk.items, 0.5 * _multVehicle)
        table.insert(VehicleDistributions.Trunk.items, "True_Moozic_BHi.CassetteREOSpeedwagonCantFightThisFeelin")
        table.insert(VehicleDistributions.Trunk.items, 0.5 * _multVehicle)
        table.insert(VehicleDistributions.Trunk.items, "True_Moozic_BHi.CassetteRickAstleyNeverGonnaGiveYouUp198")
        table.insert(VehicleDistributions.Trunk.items, 0.5 * _multVehicle)
        table.insert(VehicleDistributions.Trunk.items, "True_Moozic_BHi.CassetteRollingStonesPaintItBlack1966")
        table.insert(VehicleDistributions.Trunk.items, 0.5 * _multVehicle)
        table.insert(VehicleDistributions.Trunk.items, "True_Moozic_BHi.CassetteSaltNPepaShoop1993")
        table.insert(VehicleDistributions.Trunk.items, 0.5 * _multVehicle)
        table.insert(VehicleDistributions.Trunk.items, "True_Moozic_BHi.CassetteScatmanskibabopbadopbop1995")
        table.insert(VehicleDistributions.Trunk.items, 0.5 * _multVehicle)
        table.insert(VehicleDistributions.Trunk.items, "True_Moozic_BHi.CassetteSimonGarfunkelCecilia1970")
        table.insert(VehicleDistributions.Trunk.items, 0.5 * _multVehicle)
        table.insert(VehicleDistributions.Trunk.items, "True_Moozic_BHi.CassetteSimonGarfunkelMrsRobinson1968")
        table.insert(VehicleDistributions.Trunk.items, 0.5 * _multVehicle)
        table.insert(VehicleDistributions.Trunk.items, "True_Moozic_BHi.CassetteSineadOConnorNothingCompares2U19")
        table.insert(VehicleDistributions.Trunk.items, 0.5 * _multVehicle)
        table.insert(VehicleDistributions.Trunk.items, "True_Moozic_BHi.CassetteSirMixALotBabyGotBack1992")
        table.insert(VehicleDistributions.Trunk.items, 0.5 * _multVehicle)
        table.insert(VehicleDistributions.Trunk.items, "True_Moozic_BHi.CassetteStarshipNothingsGonnaStopUsNow19")
        table.insert(VehicleDistributions.Trunk.items, 0.5 * _multVehicle)
        table.insert(VehicleDistributions.Trunk.items, "True_Moozic_BHi.CassetteSteveEarleColoradoGirl2009")
        table.insert(VehicleDistributions.Trunk.items, 0.5 * _multVehicle)
        table.insert(VehicleDistributions.Trunk.items, "True_Moozic_BHi.CassetteSteveEarleLoretta2009")
        table.insert(VehicleDistributions.Trunk.items, 0.5 * _multVehicle)
        table.insert(VehicleDistributions.Trunk.items, "True_Moozic_BHi.CassetteSteveEarleWhiteFreightlinerBlues")
        table.insert(VehicleDistributions.Trunk.items, 0.5 * _multVehicle)
        table.insert(VehicleDistributions.Trunk.items, "True_Moozic_BHi.CassetteTacoPuttinOnTheRitz1982")
        table.insert(VehicleDistributions.Trunk.items, 0.5 * _multVehicle)
        table.insert(VehicleDistributions.Trunk.items, "True_Moozic_BHi.CassetteTalkingHeadsOnceinaLifetime1980")
        table.insert(VehicleDistributions.Trunk.items, 0.5 * _multVehicle)
        table.insert(VehicleDistributions.Trunk.items, "True_Moozic_BHi.CassetteTalkingHeadsPsychoKiller1977")
        table.insert(VehicleDistributions.Trunk.items, 0.5 * _multVehicle)
        table.insert(VehicleDistributions.Trunk.items, "True_Moozic_BHi.CassetteTearsforFearsEverybodyWantstoRul")
        table.insert(VehicleDistributions.Trunk.items, 0.5 * _multVehicle)
        table.insert(VehicleDistributions.Trunk.items, "True_Moozic_BHi.CassetteTechnoSyndromeMortalKombat1994")
        table.insert(VehicleDistributions.Trunk.items, 0.5 * _multVehicle)
        table.insert(VehicleDistributions.Trunk.items, "True_Moozic_BHi.CassetteTechnotronicPumpUpTheJam1989")
        table.insert(VehicleDistributions.Trunk.items, 0.5 * _multVehicle)
        table.insert(VehicleDistributions.Trunk.items, "True_Moozic_BHi.CassetteTheAnimalsHouseoftheRisingSun196")
        table.insert(VehicleDistributions.Trunk.items, 0.5 * _multVehicle)
        table.insert(VehicleDistributions.Trunk.items, "True_Moozic_BHi.CassetteTheBeachBoysKokomo1988")
        table.insert(VehicleDistributions.Trunk.items, 0.5 * _multVehicle)
        table.insert(VehicleDistributions.Trunk.items, "True_Moozic_BHi.CassetteTheBugglesVideoKilledtheRadioSta")
        table.insert(VehicleDistributions.Trunk.items, 0.5 * _multVehicle)
        table.insert(VehicleDistributions.Trunk.items, "True_Moozic_BHi.CassetteTheLastofUs2013")
        table.insert(VehicleDistributions.Trunk.items, 0.5 * _multVehicle)
        table.insert(VehicleDistributions.Trunk.items, "True_Moozic_BHi.CassetteTheOhHellosSoldierPoetKing2015")
        table.insert(VehicleDistributions.Trunk.items, 0.5 * _multVehicle)
        table.insert(VehicleDistributions.Trunk.items, "True_Moozic_BHi.CassetteThePoliceEverybreathyoutake1983")
        table.insert(VehicleDistributions.Trunk.items, 0.5 * _multVehicle)
        table.insert(VehicleDistributions.Trunk.items, "True_Moozic_BHi.CassetteThePoliceRoxanne1979")
        table.insert(VehicleDistributions.Trunk.items, 0.5 * _multVehicle)
        table.insert(VehicleDistributions.Trunk.items, "True_Moozic_BHi.CassetteTheProdigyBreathe1996")
        table.insert(VehicleDistributions.Trunk.items, 0.5 * _multVehicle)
        table.insert(VehicleDistributions.Trunk.items, "True_Moozic_BHi.CassetteTheShinsNewSlang2001")
        table.insert(VehicleDistributions.Trunk.items, 0.5 * _multVehicle)
        table.insert(VehicleDistributions.Trunk.items, "True_Moozic_BHi.CassetteTheStranglersGoldenBrown1981")
        table.insert(VehicleDistributions.Trunk.items, 0.5 * _multVehicle)
        table.insert(VehicleDistributions.Trunk.items, "True_Moozic_BHi.CassetteTheVerveBitterSweetSymphony1997")
        table.insert(VehicleDistributions.Trunk.items, 0.5 * _multVehicle)
        table.insert(VehicleDistributions.Trunk.items, "True_Moozic_BHi.CassetteTiffanyIThinkWereAloneNow1987")
        table.insert(VehicleDistributions.Trunk.items, 0.5 * _multVehicle)
        table.insert(VehicleDistributions.Trunk.items, "True_Moozic_BHi.CassetteTomPettyFreeFalling1988")
        table.insert(VehicleDistributions.Trunk.items, 0.5 * _multVehicle)
        table.insert(VehicleDistributions.Trunk.items, "True_Moozic_BHi.CassetteToneLocFunkyColdMedina1989")
        table.insert(VehicleDistributions.Trunk.items, 0.5 * _multVehicle)
        table.insert(VehicleDistributions.Trunk.items, "True_Moozic_BHi.CassetteTwistedSisterWereNotGonnaTakeIt1")
        table.insert(VehicleDistributions.Trunk.items, 0.5 * _multVehicle)
        table.insert(VehicleDistributions.Trunk.items, "True_Moozic_BHi.CassetteVanillaIceIceIceBaby1990")
        table.insert(VehicleDistributions.Trunk.items, 0.5 * _multVehicle)
    end
end

Events.OnInitGlobalModData.Add(initTrue_Moozic_BHiVehicleDistribution)
